
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: desk_development

test:
  <<: *default
  database: desk_test


production:
  <<: *default
  database: desk_production
  username: desk
  password: <%= ENV['DESK_THROWAWAY_DATABASE_PASSWORD'] %>
